id = "lab-icon-themes"
name = "Lab Icon Themes"
version = "0.0.1"
schema_version = 1
authors = ["vestalisvirginis", "littensy", "jmesrje"]
description = "Icon Themes for Microbiology"
repository = "https://github.com/vestalisvirginis/zed-lab-icon-theme"
